// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Model;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250108085507_1.1.3")]
    partial class _113
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Model.SqlSchool", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tb_school");
                });

            modelBuilder.Entity("WebApplication1.Model.SqlStudent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("schoolID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("schoolID");

                    b.ToTable("tb_student");
                });

            modelBuilder.Entity("WebApplication1.Model.SqlTeacher", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des7")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des8")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("des9")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("schoolID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("schoolID");

                    b.ToTable("tb_teacher");
                });

            modelBuilder.Entity("WebApplication1.Model.SqlStudent", b =>
                {
                    b.HasOne("WebApplication1.Model.SqlSchool", "school")
                        .WithMany("students")
                        .HasForeignKey("schoolID");

                    b.Navigation("school");
                });

            modelBuilder.Entity("WebApplication1.Model.SqlTeacher", b =>
                {
                    b.HasOne("WebApplication1.Model.SqlSchool", "school")
                        .WithMany("teachers")
                        .HasForeignKey("schoolID");

                    b.Navigation("school");
                });

            modelBuilder.Entity("WebApplication1.Model.SqlSchool", b =>
                {
                    b.Navigation("students");

                    b.Navigation("teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
